# Generated by Django 4.1 on 2022-09-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
    ]
